pipeline{
    agent any
    stages{
        stage("Stage1"){
            steps{
                echo "This is stage 1"
            }
            
        }
        stage("Stage2"){
            steps{
                echo "This is stage 2"
            }
            
        }
        stage("Stage3"){
            steps{
                echo "This is stage 3"
            }
            
        }
        stage("Stage4"){
            steps{
                echo "This is stage 4"
            }
            
        }
        stage("Stage5"){
            steps{
                echo "This is stage 5"
            }
            
        }
      
    }
}
